# Generated by Django 5.1.3 on 2024-12-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_matching', '0002_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/images/baseball_user_image.webp', upload_to='profile_images'),
        ),
    ]
